### ISSUE TITLE
Leave `name` out of config.yaml to let it default

### ISSUE THREAD

**Issue by rfay** [fschmittlein/WordPress-Distribution#1]
I think you'll be able to omit the instruction `Change name in the file .ddev/config.yaml to your-project (mandatory)` out of the README if you just leave 'name' out of the config.yaml. It will then default to the directory name.

Interestingly enough, you can also omit APIVersion and lots of other things and they'll just revert to defaults.

**Comment by fschmittlein** [comment]
Done. Everything unnecessary has been deleted.

**Comment by rfay** [comment]
I'm surprised to see `timezone: Europe/Berlin` in there. 

Also surprised to see you use project type 'php', but if that does all that's wanted it's fine. I guess with nginx it would be loading some wp customizations that aren't default, but you probably get those with .htaccess using apache-fpm?

**Comment by fschmittlein** [comment]
What customizations do you mean?

**Comment by rfay** [comment]
You're using apache-fpm, which has a super-generic Apache config. Currently there aren't any per-CMS apache configurations. However, each supported CMS has its own nginx configuration (and php==nocms's config is pretty ordinary. 

So I"m saying that often when people use Apache it's because they want inline .htaccess type customizations in their code.

**Comment by fschmittlein** [comment]
I have upload a .htaccess for the default config for WordPress.
