### ISSUE TITLE
git clone instructions don't work

### ISSUE THREAD

**Issue by rfay** [fschmittlein/WordPress-Distribution#2]
The readme instructions don't work:

> Clone the repository git clone https://github.com/fschmittlein/WordPress-Distribution.git your-project

```
$ git clone https://github.com/fschmittlein/WordPress-Distribution.git wordpress
fatal: destination path 'wordpress' already exists and is not an empty directory.
```

It's a bit odd cloning what's intended to be just the .ddev directory into an existing directory, I'm not sure the right way to do it. Tell them to clone and them cp -r the .ddev directory?

**Comment by fschmittlein** [comment]
The distribution is for new projects and there is no existing directory.

**Comment by rfay** [comment]
The changed README helps with this, but you'll probably want to add a new section to the start of the README, something like "What this distribution does", explaining that it's for a *brand new* WP project, whose directory doesn't even exist yet. (and as discussed elsewhere, what's added to it and why)
