### ISSUE TITLE
Custom commands must be executable

### ISSUE THREAD

**Issue by rfay** [fschmittlein/WordPress-Distribution#3]
When I try `ddev wordpress` on macOS I get 

```
 ddev wordpress
Failed to run wordpress ; error=fork/exec /Users/rfay/workspace/wordpress/.ddev/commands/host/wordpress: permission denied
```

Same problem with wp-create

```
bash: .ddev/commands/web/wp-create: Permission denied
```

You can check it in with the executable bit set and avoid this problem. Were you testing on Windows?

**Comment by fschmittlein** [comment]
At the moment I can only test under Windows. How should I set the executable bit?

**Comment by fschmittlein** [comment]
I set the executable bit with "git add --chmod=+x ...". Can you please test it again?

**Comment by rfay** [comment]
A fresh clone shows success:
```
$ cd .ddev/commands/
rfay@rfay-mbp-2017:~/workspace/wpgen/.ddev/commands$ ls -l */*
-rwxr-xr-x  1 rfay  staff   218 Aug 21 18:48 host/wordpress
-rwxr-xr-x  1 rfay  staff  1761 Aug 21 18:48 web/wp-create
-rwxr-xr-x  1 rfay  staff   285 Aug 21 18:48 web/wp-recreate
```

**Comment by rfay** [comment]
I didn't know about `git add --chmod=+x` - had no idea! I've always just set the mode and added. I know that doesn't work in some setups.

**Comment by rfay** [comment]
All set now!
